
name: Swift CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Show Swift Version
        run: swift --version
        
      - name: Install SwiftLint
        run: brew install swiftlint

      - name: Run SwiftLint
        run: swiftlint
        
      - name: Build
        run: |
            xcodebuild \
                test \
                -project MySwiftyRepo.xcodeproj \
                -scheme MySwiftyRepo \
                -destination 'platform=iOS Simulator,name=iPhone 17' \
                -enableCodeCoverage YES \
                -resultBundlePath TestResults.xcresult \
                CODE_SIGNING_ALLOWED=NO \

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: TestResults
          path: TestResults.xcresult
